feat(superset): deploy a lightweight version on staging
wmde/wbaas-deploy pull request #1660
Opened 2024-06-26 14:54 UTC by AndrewKostka

2024-06-27 07:33 UTC, m90 commented
One question from my end: Superset does have user management, so it would also be possible to expose it to the public internet (by adding an ingress like `superset.wikibase.dev`) and then create a dedicated superset user for everyone that needs access. This would mean we can grant access to semi-technical folk without having to use Tailscale and such. Also, it gives us some sort of insights of who's changed what in Superset itself.

Are there any strong reasons for not using the built in access control and instead use our own?

2024-06-27 08:39 UTC, tarrow commented
I'm somewhat reading between the lines here but my assumption was that the direction this patch was going in is a kind of defence in depth style: we would also generate individual users for superset (and this just contains some admin bootstrapping user) but we're going to have an initial layer of protection from tailscale since superset would be a very valuable service to compromise (it has access to user account details etc.)

Is that what you were thinking @AndrewKostka ?

2024-06-27 10:14 UTC, tarrow commented
Cool, are you expecting this chart to *only* go as far as staging then? If that's the case I'll review it with that in mind

2024-06-28 11:36 UTC, tarrow requested changes
Couple of minor thoughts but also a blocker in that I wasn't able to apply this chart locally. I'd also like to talk a look at the thing after I can apply it locally and see it all wired up

2024-06-28 11:36 UTC, tarrow commented on charts/superset/values.yaml
> +entrypoint: |
What was the thinking behind sticking this in the values file rather than in one of the templates?

2024-06-28 11:36 UTC, tarrow commented on charts/superset/templates/sqlite-pvc.yaml
> +  persistentVolumeReclaimPolicy: Retain
I can't apply the chart due to this:
```
  Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(PersistentVolumeClaim.spec): unknown field "persistentVolumeReclaimPolicy" in io.k8s.api.core.v1.PersistentVolumeClaimSpec, ValidationError(PersistentVolumeClaim.spec): unknown field "storageClass" in io.k8s.api.core.v1.PersistentVolumeClaimSpec]
  Error: plugin "diff" exited with error
```

I wonder if you managed to? I think this key is only valid on the PV not the PVC but in any case you might rather add this to the storageclass (or instead use a stateful set in place of the deployment). See this S/O post for some thoughts https://stackoverflow.com/questions/50458165/kubernetes-how-to-do-dynamic-persistentvolumeclaim-with-persistentvolumereclaim

2024-06-28 11:36 UTC, tarrow commented on charts/superset/templates/deployment.yaml
> +kind: Deployment
As per the other comment I wonder if this would better be a statefulset?

2024-07-03 07:55 UTC, tarrow commented on charts/superset/templates/statefulset.yaml
> +spec:
This won't apply without a `serviceName`.

```
STDERR:
  Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1.StatefulSetSpec
  Error: plugin "diff" exited with error
```

2024-07-03 07:56 UTC, tarrow commented on charts/superset/values.yaml
> +  pip install mysqlclient==2.1.0
fair enough!

2024-07-03 08:12 UTC, tarrow commented on charts/superset/templates/statefulset.yaml
> +spec:
Patch from me to make this apply:
```
diff --git a/charts/superset/templates/statefulset.yaml b/charts/superset/templates/statefulset.yaml
index b8007cd..1c31463 100644
--- a/charts/superset/templates/statefulset.yaml
+++ b/charts/superset/templates/statefulset.yaml
@@ -102,3 +102,4 @@ spec:
         resources:
           requests:
             storage: {{ .Values.storageSize }}
+  serviceName: foo
\ No newline at end of file
```

2024-07-04 13:03 UTC, tarrow approved these changes
amazing; let's go then!

2024-07-04 14:06 UTC, merged